---
title: "Problem Set 07"
author: "Leo Camino, ltc31"
date: today
date-format: iso
format: 
  html:
    embed-resources: true
editor: source
---
## Problem 1: Data Wrangling

```{r}
raw_data <- read.csv("C:/Users/leoto/Desktop/Microbescope_original_data.csv")
clean_data <- read.csv("C:/Users/leoto/Desktop/microbescope_clean.csv")

# Load required libraries
library(tidyverse)

#Here I remove the unnecessary first section that includes notes and comments on the .csv file.
raw_data <- raw_data[-1, ]

#here I selected the specific columns I wanted to include.
raw_data <- raw_data %>%
  select(X, case.fatality.rate, average.basic.reproductive.rate, pathogen.type, primary.mode.of.transmission)

#Lastly, I changed the names to the accurate ones. 
raw_data <- raw_data %>%
  rename(
    disease = X,
    case_fatality_rate = case.fatality.rate,
    average_basic_reproductive_rate = average.basic.reproductive.rate,
    pathogen_type = pathogen.type,
    primary_mode_of_transmission = primary.mode.of.transmission
  )

```

## Problem 2: Graphing using my wrangled data.
```{r}

library(ggplot2)
library(ggrepel)

my_colors <- c("#335060","#9d9353","#e13698","#37251e",
               "#81aea3","#ff8106","#888888", "firebrick")

clean_data |>
  drop_na() |>
  filter(average_basic_reproductive_rate < 20) |>
  ggplot(aes(x = average_basic_reproductive_rate,
             y = case_fatality_rate, 
             shape = pathogen_type,
             color = primary_mode_of_transmission)) +
  # draw background rectangles
  geom_rect(aes(ymin=0, ymax=1,xmin=-1,xmax=21), 
            alpha=0.003,color='#D3D3D3', linetype="dashed") +
  geom_rect(aes(ymin=20, ymax=50,xmin=-1,xmax=21), 
            alpha=0.003,color='#D3D3D3', linetype="dashed") +  
  # draw points
  geom_point(size=4, alpha=0.6) + 
  scale_color_manual(values = my_colors) +
  # draw labels
  geom_text_repel(aes(label=disease), 
                  size = 4,
                  force = 1,
                  force_pull = 2) +  
  scale_y_sqrt(breaks=c(0,0.1,1,seq(10,100,10)),
               minor_breaks = NULL, 
               sec.axis = dup_axis(name = "",
                                   breaks = c(0.2, 8, 35, 80),
                                   labels = c("Less deadly", "Quite deadly", "Deadly", "Extremely Deadly"))) +

  coord_cartesian(xlim = c(0,20)) +
  labs(x = "Contagiousness: R0",
       y = "Deadliness: Case fatality rate (%)") +
  
  theme_bw() +
  theme(legend.position = "top", legend.background = element_rect(size = 0.5, colour='grey')) +
  guides(color = guide_legend(title = "Primary Mode of Transmission"),
         shape = guide_legend(title = "Pathogen Type")) 
```

